<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="soni" name="Alternate Cube Report16" tests="5" failures="0" timestamp="11 Jan 2017 12:54:35 GMT" time="45.64" errors="0">
  <testcase name="suiteExecution" time="9.044" classname="com.eqtechnologic.framework.TestSuite">
    <failure type="com.eqtechnologic.exceptions.ExcelConnectionException" message="Some IOException occurred while trying to read the excel sheet: LOGIN in directory: .\Templates\Keywords.xls. Please make sure that the test suite/test cases are present at the right path">
      <![CDATA[com.eqtechnologic.exceptions.ExcelConnectionException: Some IOException occurred while trying to read the excel sheet: LOGIN in directory: .\Templates\Keywords.xls. Please make sure that the test suite/test cases are present at the right path
	at com.eqtechnologic.util.ExcelProcessor.<init>(ExcelProcessor.java:70)
	at com.eqtechnologic.framework.TestSuite.suiteExecution(TestSuite.java:193)
	at com.eqtechnologic.framework.Interpreter.processKeywordAtRowNum(Interpreter.java:156)
	at com.eqtechnologic.framework.Interpreter.iterateRows(Interpreter.java:108)
	at com.eqtechnologic.framework.TestSuite.suiteExecution(TestSuite.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:73)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.FileNotFoundException: .\Templates\Keywords.xls (The system cannot find the path specified)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at com.eqtechnologic.util.ExcelProcessor.<init>(ExcelProcessor.java:64)
	... 19 more
]]>
    </failure>
  </testcase> <!-- suiteExecution -->
  <testcase name="suiteExecution" time="8.591" classname="com.eqtechnologic.framework.TestSuite">
    <failure type="com.eqtechnologic.exceptions.ExcelConnectionException" message="Some IOException occurred while trying to read the excel sheet: LOGIN in directory: .\Templates\Keywords.xls. Please make sure that the test suite/test cases are present at the right path">
      <![CDATA[com.eqtechnologic.exceptions.ExcelConnectionException: Some IOException occurred while trying to read the excel sheet: LOGIN in directory: .\Templates\Keywords.xls. Please make sure that the test suite/test cases are present at the right path
	at com.eqtechnologic.util.ExcelProcessor.<init>(ExcelProcessor.java:70)
	at com.eqtechnologic.framework.TestSuite.suiteExecution(TestSuite.java:193)
	at com.eqtechnologic.framework.Interpreter.processKeywordAtRowNum(Interpreter.java:156)
	at com.eqtechnologic.framework.Interpreter.iterateRows(Interpreter.java:108)
	at com.eqtechnologic.framework.TestSuite.suiteExecution(TestSuite.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:73)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.FileNotFoundException: .\Templates\Keywords.xls (The system cannot find the path specified)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at com.eqtechnologic.util.ExcelProcessor.<init>(ExcelProcessor.java:64)
	... 19 more
]]>
    </failure>
  </testcase> <!-- suiteExecution -->
  <testcase name="suiteExecution" time="8.948" classname="com.eqtechnologic.framework.TestSuite">
    <failure type="com.eqtechnologic.exceptions.ExcelConnectionException" message="Some IOException occurred while trying to read the excel sheet: LOGIN in directory: .\Templates\Keywords.xls. Please make sure that the test suite/test cases are present at the right path">
      <![CDATA[com.eqtechnologic.exceptions.ExcelConnectionException: Some IOException occurred while trying to read the excel sheet: LOGIN in directory: .\Templates\Keywords.xls. Please make sure that the test suite/test cases are present at the right path
	at com.eqtechnologic.util.ExcelProcessor.<init>(ExcelProcessor.java:70)
	at com.eqtechnologic.framework.TestSuite.suiteExecution(TestSuite.java:193)
	at com.eqtechnologic.framework.Interpreter.processKeywordAtRowNum(Interpreter.java:156)
	at com.eqtechnologic.framework.Interpreter.iterateRows(Interpreter.java:108)
	at com.eqtechnologic.framework.TestSuite.suiteExecution(TestSuite.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:73)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.FileNotFoundException: .\Templates\Keywords.xls (The system cannot find the path specified)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at com.eqtechnologic.util.ExcelProcessor.<init>(ExcelProcessor.java:64)
	... 19 more
]]>
    </failure>
  </testcase> <!-- suiteExecution -->
  <testcase name="suiteExecution" time="8.996" classname="com.eqtechnologic.framework.TestSuite">
    <failure type="com.eqtechnologic.exceptions.ExcelConnectionException" message="Some IOException occurred while trying to read the excel sheet: LOGIN in directory: .\Templates\Keywords.xls. Please make sure that the test suite/test cases are present at the right path">
      <![CDATA[com.eqtechnologic.exceptions.ExcelConnectionException: Some IOException occurred while trying to read the excel sheet: LOGIN in directory: .\Templates\Keywords.xls. Please make sure that the test suite/test cases are present at the right path
	at com.eqtechnologic.util.ExcelProcessor.<init>(ExcelProcessor.java:70)
	at com.eqtechnologic.framework.TestSuite.suiteExecution(TestSuite.java:193)
	at com.eqtechnologic.framework.Interpreter.processKeywordAtRowNum(Interpreter.java:156)
	at com.eqtechnologic.framework.Interpreter.iterateRows(Interpreter.java:108)
	at com.eqtechnologic.framework.TestSuite.suiteExecution(TestSuite.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:73)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.FileNotFoundException: .\Templates\Keywords.xls (The system cannot find the path specified)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at com.eqtechnologic.util.ExcelProcessor.<init>(ExcelProcessor.java:64)
	... 19 more
]]>
    </failure>
  </testcase> <!-- suiteExecution -->
  <testcase name="suiteExecution" time="10.019" classname="com.eqtechnologic.framework.TestSuite">
    <failure type="com.eqtechnologic.exceptions.ExcelConnectionException" message="Some IOException occurred while trying to read the excel sheet: LOGIN in directory: .\Templates\Keywords.xls. Please make sure that the test suite/test cases are present at the right path">
      <![CDATA[com.eqtechnologic.exceptions.ExcelConnectionException: Some IOException occurred while trying to read the excel sheet: LOGIN in directory: .\Templates\Keywords.xls. Please make sure that the test suite/test cases are present at the right path
	at com.eqtechnologic.util.ExcelProcessor.<init>(ExcelProcessor.java:70)
	at com.eqtechnologic.framework.TestSuite.suiteExecution(TestSuite.java:193)
	at com.eqtechnologic.framework.Interpreter.processKeywordAtRowNum(Interpreter.java:156)
	at com.eqtechnologic.framework.Interpreter.iterateRows(Interpreter.java:108)
	at com.eqtechnologic.framework.TestSuite.suiteExecution(TestSuite.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:73)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.FileNotFoundException: .\Templates\Keywords.xls (The system cannot find the path specified)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at com.eqtechnologic.util.ExcelProcessor.<init>(ExcelProcessor.java:64)
	... 19 more
]]>
    </failure>
  </testcase> <!-- suiteExecution -->
</testsuite> <!-- Alternate Cube Report16 -->
